# Generated by Django 4.2 on 2025-09-21 22:48

from django.db import migrations,models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field =models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True
            ) ,
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field= models.DateTimeField(auto_now_add=True,null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(max_digits=10,decimal_places=2,default=0),
        ),
    ]
